name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Copy files to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        rsync -avz --exclude=".git" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/app

    - name: Restart server
      if: ${{ failure() != true }}  # Skip if any previous steps failed
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USERNAME }}/app
          pm2 stop all || true
          pm2 start index.js --name "backend-api" --watch
        EOF
notifications:
  failure:
    if: failure()
    name: Send Failure Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: '${{ secrets.EMAIL_USERNAME }}'
          password: '${{ secrets.EMAIL_PASSWORD }}'
          subject: 'Workflow Failed - ${{ github.repository }}'
          to: your@email.com
          from: your@email.com
          body: >
            The workflow for ${{ github.repository }} on branch ${{ github.ref
            }} failed.
  success:
    if: success()
    name: Send Success Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: '${{ secrets.EMAIL_USERNAME }}'
          password: '${{ secrets.EMAIL_PASSWORD }}'
          subject: 'Workflow Succeeded - ${{ github.repository }}'
          to: your@email.com
          from: your@email.com
          body: >
            The workflow for ${{ github.repository }} on branch ${{ github.ref
            }} succeeded.

