name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Copy files to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        rsync -avz --exclude=".git" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/app
        
    - name: Restart server
      if: ${{ failure() != true }}  # Skip if any previous steps failed
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
       
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
         cd /home/${{ secrets.SSH_USERNAME }}/app
       
         pkill -f "node index.js" || true
         nohup node index.js &
        EOF

    #Notification Section (tells us if the workflow was success or failure) 
 
 send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Success Notification
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Workflow Success Notification"
          body: "The workflow executed successfully - Code is copied to the Virtual Machine/Server"
          to: "riteshkoranga5@gmail.com"
          from: "deployment2610@gmail.com"
          secure: true

      - name: Send Failure Notification
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Workflow Failure Notification"
          body: "The workflow encountered an error and failed."
          to: "riteshkoranga5@gmail.com"
          from: "deployment2610@gmail.com"
          secure: true

         

    
    

      
        
        


      
   
     
            
